var str="Hello world!";
console.log(str.charAt(0));
var str ="Hello world!";
console.log(str.charCodeAt(0));
var str1="Hello";
var str2="World!";
console.log(str1.concat(" ",str2));
var str="Hello World!";
console.log(str.endsWith("World!"));
var str="Hello World!";
console.log(str.toUpperCase());
var str="Hello World!";
console.log(str.toLowerCase());
var str="Hello World!";
console.log(str.length);
var str1="Hello World!";
var str2="World!";
console.log(str2.slice(0,3));